# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ccc202990c31546a4f1fee7a7d927e5840dca8ed66b6cbb733a9d9104e2c065b4baa66a49be2b0f81e65f5c2902fe606f8b6b3e25a4ba1a081fca33be38f0f1

test:
  secret_key_base: a52980ed09d657774b8fa3981a6da1c90630f8453f33a79b7c9ed24c9ea9cbb5cc511d41fb34d4b10f9d1d94a869d9f6a11d22a2d84ec86f435c545c4e21d39f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
